# Generated by Django 6.0.2 on 2026-03-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
