# Generated by Django 6.0.2 on 2026-03-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
